doctraining/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from doctraining import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),

    # path('accounts/password_change/', auth_views.PasswordChangeView.as_view(template_name='change-password.html')),
    path('contas/alterar_senha/', auth_views.PasswordChangeView.as_view(template_name='registration/alterar_senha.html'), name='password_change'),
    path('contas/alterar_senha/completo/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/alterar_senha_completo.html'), name='password_change_done'),
    path('contas/recuperar_senha/', auth_views.PasswordResetView.as_view(template_name='registration/recuperar_senha.html'), name='password_reset'),
    path('contas/recuperar_senha/completo/', auth_views.PasswordResetDoneView.as_view(template_name='registration/recuperar_senha_completo.html'), name='password_reset_done'),
    path('contas/resetar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/confirmar_recuperacao.html'), name='password_reset_confirm'),
    path('contas/resetar/completo/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/confirmar_recuperacao_completo.html'), name='password_reset_complete'),

    #path(aliasURL+'', include('hide_herokuapp.urls')),
    path('', include('doctrainingapp.urls',namespace='doctrainingapp'))
]


urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static('/media/',document_root=settings.MEDIA_ROOT)



# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

doctrainingapp/urls.py
from .views_pack import views_versao, views_api, views_ia, views_firebase, views_areafase, views_user, views_backup, views_area, views_conteudo, views_fases, views_upload
from django.urls import path
from .views  import  *
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

app_name="doctrainingapp"


urlpatterns = [

    path('', index, name='index'),
    path('login/',auth_views.LoginView.as_view(template_name="login.html",redirect_authenticated_user=True),name='login'),#,redirect_authenticated_user=True
    path('logout/',sair,name='logout'),

    path('doctraining/',login_required(doctraining),name='doctraining'),

    path('data_firebase/',login_required(data_firebase),name='data_firebase'),
    path('get_rank_xp_firebase/',login_required(get_rank_xp_firebase),name='get_rank_xp_firebase'),
    
    path('user/novo/',login_required(views_user.UserCreate.as_view()),name='user_create'),
    path('user/perfil/editar/<int:pk>/',login_required(views_user.PerfilUpdate.as_view()),name='perfil_update'),
    path('user/<int:pk>/',login_required(views_user.UserUpdate.as_view()),name='user_update'),
    path('usuarios/',login_required(usuarios),name='usuarios'),
    path('user/ativar/<int:pk>/',login_required(usuario_ativar),name='user_ativar'),
    path('user/desativar/<int:pk>/',login_required(usuario_desativar),name='user_desativar'),




    #WEB Solicitações Editar, deletar e novo
    path('casos_clinicos/solicitar/editar/<int:pk>/',login_required(solicitar_editar_caso_clinico), name='solicitar_editar_caso_clinico'),
    path('casos_clinicos/solicitar/novo/',login_required(solicitar_novo_caso_clinico),name='solicitar_novo_caso_clinico'),
    path('casos_clinicos/solicitar/delete/<int:pk>/',login_required(solicitar_deletar_caso_clinico), name='solicitar_deletar_caso_clinico'),



    #WEB Visualizar dados
    path('casos_clinicos/',login_required(casos_clinicos),name='casos_clinicos'),


    #Solicitações de Alteração de dados
    path('casos_clinicos/solicitacoes/',login_required(solicitacoes_alteracao_casos_clinicos),name='solicitacoes_alteracao_casos_clinicos'),
    path('casos_clinicos/solicitacoes/aceitar/<int:pk>/',login_required(aceitar_solicitacao_alteracao_caso_clinico),name='aceitar_solicitacao_alteracao_caso_clinico'),
    path('casos_clinicos/solicitacoes/rejeitar/<int:pk>/',login_required(rejeitar_solicitacao_alteracao_caso_clinico),name='rejeitar_solicitacao_alteracao_caso_clinico'),

    path('casos_clinicos/solicitacoes/log/',login_required(log_solicitacoes_alteracao_casos_clinicos),name='log_solicitacoes_alteracao_casos_clinicos'),

    #Doenca
    path('doenca/<int:pk>/',login_required(doenca),name='doenca'),
    path('doenca/solicitacoes/delete/<int:pk>/',login_required(solicitar_deletar_doenca),name='solicitar_deletar_doenca'),
    path('doenca/nova/',login_required(solicitar_nova_doenca),name='solicitar_nova_doenca'),

    #Sintoma
    path('sintoma/<int:pk>/',login_required(sintoma),name='sintoma'),
    path('sintoma/solicitacoes/delete/<int:pk>/',login_required(solicitar_deletar_sintoma),name='solicitar_deletar_sintoma'),
    path('sintoma/novo/',login_required(solicitar_novo_sintoma),name='solicitar_novo_sintoma'),


    #SALAS
    #path('salas/todas/',login_required(todas_salas),name='todas_salas'),
    path('salas/nova/<int:area_pk>',sala_add,name='nova_sala'),
    path('salas/editar/<int:pk>/',login_required(Editar_Sala.as_view()),name='editar_sala'),
    path('salas/deletar/<int:pk>/',login_required(Deletar_Sala.as_view()),name='delete_sala'),

    # FASES
    path('fases/todas/', login_required(views_fases.todas_fases), name='todas_fases'),
    path('fases/nova/<int:area_pk>', views_fases.fase_add, name='nova_fase'),
    path('fases/editar/<int:pk>/', login_required(views_fases.Editar_Fase.as_view()), name='editar_fase'),
    path('fases/deletar/<int:pk>/', login_required(views_fases.Deletar_Fase.as_view()), name='delete_fase'),

    # PERGUNTAS FASES
    path('fases/<int:pk_fase>/perguntas/nova/',login_required(views_fases.nova_pergunta),name='nova_perguntafase'),
    path('fases/<int:pk_fase>/perguntas/',login_required(views_fases.todas_perguntas),name='todas_perguntasfase'),
    path('fases/editar/perguntas/<int:pk>/',login_required(views_fases.Editar_PerguntaFase.as_view()),name='editar_perguntafase'),
    path('fases/perguntas/deletar/<int:pk>/',login_required(views_fases.Deletar_PerguntaFase.as_view()),name='delete_perguntafase'),


    # PERGUNTAS
    path('salas/<int:pk_sala>/perguntas/nova/',login_required(nova_pergunta),name='nova_pergunta'),
    path('salas/<int:pk_sala>/perguntas/',login_required(todas_perguntas),name='todas_perguntas'),
    path('salas/editar/perguntas/<int:pk>/',login_required(Editar_Pergunta.as_view()),name='editar_pergunta'),
    path('salas/perguntas/deletar/<int:pk>/',login_required(Deletar_Pergunta.as_view()),name='delete_pergunta'),




    #WEB SERVICE
    path('api/',login_required(views_api.api),name='api'),
    path('api/casos_clinicos/nome_doencas/', views_api.nome_doencas_casos_clinicos_api,name='nome_doencas_casos_clinicos_api'),
    path('api/casos_clinicos/nome_sintomas/', views_api.nome_sintomas_casos_clinicos_api,name='nome_sintomas_casos_clinicos_api'),
    path('api/casos_clinicos/todos/', views_api.todos_casos_clinicos_doencas_sintomas_api,name='todos_casos_clinicos_doencas_sintomas_api'),
    path('api/casos_clinicos/um/', views_api.um_caso_clinico_doenca_sintomas_api,name='um_caso_clinico_doenca_sintomas_api'),
    path('api/salas/<int:pk_sala>/perguntas/', views_api.perguntas_de_uma_sala_api,name='perguntas_de_uma_sala_api'),
    path('api/salas/', views_api.todos_salas_api,name='todos_salas_api'),
    path('api/area/salas/', views_api.areas_salas_api,name='areas_salas_api'),
    path('api/areasfases/', views_api.areasFase,name='areasfases'),
    path('api/fases/<int:pk_area>', views_api.fases_api, name='fases_api'),
    url(r"^api/versao/(?P<versao_versao>\d+\.\d+)$", views_api.versao_api, name='versao-api'),
    # url(r"^item/value/(?P<dollar>\d+\.\d+)$", views.show_item, name="show-item"),
    path('api/conteudo/todos/', views_api.conteudos_api, name='conteudos_api'),
    path('api/datatime/', views_api.getdatatime, name='datatime'),


    #APRENDIZADO DE MÁQUINA controle das threads
    path('ativar_am/', login_required(views_ia.ativar_am), name='ativar_am'),
    # path('desativar_am/', login_required(desativar_am), name='desativar_am'),
    path('status_am/', login_required(views_ia.status_am), name='status_am'),
    path('am_agora/', login_required(views_ia.am_agora), name='am_agora'),

    #BACKUP E RESTAURAR BACKUP
    #path('ler_dados_salvar/',login_required(views_backup.ler_dados_salvar)),#Caso o backup sejá restaurado é interessante apagar todos os dados da tabela caso clinico,doenca e sintomas pois serão novamente salvos e pode haver duplicação de caso clinico
    #path('ler_dados_salvar/',views_backup.ler_dados_salvar),#Caso o backup sejá restaurado é interessante apagar todos os dados da tabela caso clinico,doenca e sintomas pois serão novamente salvos e pode haver duplicação de caso clinico
    #path('gerar_csv/',login_required(views_backup.gerar_csv)),

    #VERSIONAMENTO
    path('versao', views_versao.versao_list, name='lista-versao'),
    #path('versao/<int:pk>', versao_view, name='view-versao'),
    path('versao/add', views_versao.versao_add, name='add-versao'),
    path('versao/edit/<int:pk>', views_versao.versao_edit, name='edit-versao'),
    path('versao/delete/<int:pk>', views_versao.versao_delete, name='delete-versao'),
    #path('versao/delete/<int:pk>', versao_delete, name='delete-versao'),


    #AREAS
    path('areas/', views_area.area_list, name='areas_list'),
    path('areas/fases/<int:pk_area>', views_fases.todas_fases, name='area_fases'),
    path('areas/salas/<int:pk_area>', todas_salas, name='area_salas'),
    path('area/add', views_area.area_add, name='area_add'),
    path('area/edit/<int:pk>', views_area.area_edit, name='area_edit'),
    path('area/delete/<int:pk>', views_area.area_delete, name='area_delete'),

    #AREAFASES
    path('areafase/', views_areafase.area_list, name='areas_fase_list'),
    path('areafase/add', views_areafase.area_add, name='area_fase_add'),
    path('areafase/edit/<int:pk>', views_areafase.area_edit, name='area_fase_edit'),
    path('areafase/delete/<int:pk>', views_areafase.area_delete, name='area_fase_delete'),


    #CONTEUDO
    path('conteudos/', views_conteudo.conteudo_list, name='list-conteudo'),
    #path('conteudo/add', views_conteudo.conteudo_add, name='add-conteudo'),
    #path('conteudo/edit/<int:pk>', views_conteudo.conteudo_edit, name='edit-conteudo'),
    path('conteudo/view/<int:pk>', views_conteudo.conteudo_view, name='view-conteudo'),
    path('conteudo/delete/<int:pk>', views_conteudo.conteudo_delete, name='delete-conteudo'),
#############
    path('conteudo_list', views_conteudo.ConteudoListView.as_view(), name='person_changelist'),
    path('conteudo_add/', views_conteudo.ConteudoCreateView.as_view(), name='conteudo_add'),
    path('conteudo/edit/<int:pk>/', views_conteudo.ConteudoUpdateView.as_view(), name='conteudo_edit'),
    path('ajax/load-cities/', views_conteudo.load_cities, name='ajax_load_cities'),


    #UPLOADS
    path('upload-area/', views_upload.area_upload, name="area_upload"),
    path('upload-areafase/', views_upload.areafase_upload, name="areafase_upload"),
    path('upload-sala/', views_upload.sala_upload, name="sala_upload"),
    path('upload-fase/', views_upload.fase_upload, name="fase_upload"),
    path('upload-pergunta-sala/', views_upload.pergunta_sala_upload, name="pergunta_sala_upload"),
    path('upload-pergunta-fase/', views_upload.pergunta_fase_upload, name="pergunta_fase_upload"),
    path('upload', views_upload.upload, name='upload'),

doctrainingapp/forms.py
import io
from django.forms import ModelForm
from django import forms
import json

from doctrainingapp.models import Versao, Area, Conteudo, Fase, Sala, AreaFase



class VersaoForm(ModelForm):
    class Meta:
        model = Versao
        fields = ['versao', 'informacao', 'atualizacao_critica']


    def __init__(self, *args, **kwargs):
        super(VersaoForm, self).__init__(*args, **kwargs)

        self.fields['versao'].widget.attrs['class'] = 'ui form'
        self.fields['informacao'].widget.attrs['class'] = 'ui form'
        self.fields['atualizacao_critica'].widget.attrs['class'] = 'ui form'

class AreaForm(ModelForm):
    class Meta:
        model = Area
        fields = ['nome']


    def __init__(self, *args, **kwargs):
        super(AreaForm, self).__init__(*args, **kwargs)

        self.fields['nome'].widget.attrs['class'] = 'ui form'

class AreaFaseForm(ModelForm):
    class Meta:
        model = AreaFase
        fields = ['nome']


    def __init__(self, *args, **kwargs):
        super(AreaFaseForm, self).__init__(*args, **kwargs)

        self.fields['nome'].widget.attrs['class'] = 'ui form'

class FaseForm(ModelForm):
    class Meta:
        model = Fase
        fields = ['nome_fase','descricao', 'dificuldade', 'imagem1', 'imagem2', 'imagem3' ]


    def __init__(self, *args, **kwargs):
        super(FaseForm, self).__init__(*args, **kwargs)

        self.fields['nome_fase'].widget.attrs['class'] = 'ui form'
        self.fields['descricao'].widget.attrs['class'] = 'ui form'
        self.fields['dificuldade'].widget.attrs['class'] = 'ui form'

class SalaForm(ModelForm):
    class Meta:
        model = Sala
        fields = ['nome_sala','descricao' ]


    def __init__(self, *args, **kwargs):
        super(SalaForm, self).__init__(*args, **kwargs)

        self.fields['nome_sala'].widget.attrs['class'] = 'ui form'
        self.fields['descricao'].widget.attrs['class'] = 'ui form'

class ConteudoForm(ModelForm):


    class Meta:
        model = Conteudo
        fields = ['area','sala', 'titulo', 'conteudo', 'link', 'referencia', 'imagem1', 'imagem2', 'imagem3']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['sala'].queryset = Sala.objects.none()

        if 'area' in self.data:
            try:
                country_id = int(self.data.get('area'))
                self.fields['sala'].queryset = Sala.objects.filter(area_id=country_id).order_by('nome_sala')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['sala'].queryset = self.instance.area.sala_set.order_by('nome_sala')


class UploadAreaForm(forms.Form):
    data_file = forms.FileField()

doctrainingapp/templates/area-edit.html
{% include 'cabecalho2.html' %}


<h2>Editar Área das Questões/Glossário</h2>

{% if messages %}
    <ul class="messages">
            {% for message in messages %}
                <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.tags == 'success' %}
                        <font color="green">{{ message }}</font>
                    {% elif message.tags == 'error' %}
                        <font color="red">{{ message }}</font>
                    {% else %}
                        <!-- warning -->
                        <font color="">{{ message }}</font>
                    {% endif %}
                </li>
            {% endfor %}
    </ul>
{% endif %}



<form class="ui form" action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
{% for field in form %}
 {{ field.errors }}
<div class=" field">
    <label>{{field.label}}</label>
  <p></p>
  {{ field }}
</div>
<p></p>

{% endfor %}
    <!-- <p>*Obs: Marque a checkbox caso for verdadeiro</p> -->
    <button class="ui button positive" type="submit">Salvar</button>
    <a href="javascript:window.history.go(-1)" class="ui brown button" >Cancelar</a>
</form>

doctrainingapp/templates/area-fase-add.html
{% include 'cabecalho2.html' %}


<h2>Adicionar Área para Casos Clínicos</h2>

{% if messages %}
    <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.tags == 'success' %}
                        <font color="green">{{ message }}</font>
                    {% elif message.tags == 'error' %}
                        <font color="red">{{ message }}</font>
                    {% else %}
                        <!-- warning -->
                        <font color="">{{ message }}</font>
                    {% endif %}
                </li>
            {% endfor %}
    </ul>
{% endif %}



<form class="ui form" action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
{% for field in form %}
 {{ field.errors }}
<div class=" field">
  <label>{{ field.label_tag }}</label>
    {{ field.help_text|safe }}
  <p></p>
  {{ field }}
</div>
<p></p>

{% endfor %}
    <button class="ui button positive" type="submit">Salvar</button>
    <a href="javascript:window.history.go(-1)" class="ui brown button" >Cancelar</a>
</form>










</div>

</div>
<!-- Cabecalho -->

<div>



{% include 'rodape.html' %}

doctrainingapp/templates/area-list.html
{% include 'cabecalho2.html' %}

<h1>
  Área de Questões/Glossário
</h1>

{% if messages %}
    <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.tags == 'success' %}
                        <font color="green">{{ message }}</font>
                    {% elif message.tags == 'error' %}
                        <font color="red">{{ message }}</font>
                    {% else %}
                        <!-- warning -->
                        <font color="blue">{{ message }}</font>
                    {% endif %}
                </li>
            {% endfor %}
    </ul>
{% endif %}


<a href="{% url 'doctrainingapp:area_add' %}" class="ui button positive" > Nova Área </a>
 <p>As áreas servem para questões e para o Glossário.</p>
 <p>Em "Salas de Questões/Glossário" é possivel adicional as questões.</p>

<p></p>
<!-- <div style="overflow: auto; width: 100%; height: 500px; border:solid 1px; position: relative;"> -->
  <!-- <table class="ui celled striped table"> -->

  <table id="example" class="ui celled table" style="width:100%">
    <thead>
      <tr>
        <!-- Colunas da tabela -->
        <th>Área de Questões/Glossário</th>
          <th>Salas de Questões / Subáreas Glossário</th>
         <th>Edição</th>
          <th>Deletar</th>
        <!-- colunas da tabela -->

        <!-- <th></th> -->
        <!-- <th colspan="3"> </th> -->
      </tr>
    </thead>

  <!--  Opções em cima da tabela-->

    <tbody>
      {% for area in areas  %}
            <tr>
              <td><b> {{area.nome}} </b></td>
                <td>
                      <a href="{% url 'doctrainingapp:area_salas' area.pk %}" >   Salas de Questões  <i class="edit outline icon"></i> </a>


              </td>

              <td>
                      <a href="{% url 'doctrainingapp:area_edit' area.pk %}" >   Editar <i class="edit outline icon"></i> </a>


              </td>
                <td>
                    <a href="{% url 'doctrainingapp:area_delete' area.pk %}" >   Excluir <i class=></i> </a>
                </td>
              <!-- <td>
                  {% if request.user.pk == sala.responsavel_sala.pk or request.user.is_staff%}
                      <a href="" class="ui red button" >   Deletar </a>
                  {% endif %}
              </td> -->


            </tr>
      {% endfor %}

    </tbody>
  </table>

</div>













</div>

</div>
<!-- Cabecalho -->

<div>



{% include 'rodape.html' %}

doctrainingapp/templates/dropdown_list_options.html
<option value="">---------</option>
{% for sala in salas %}
<option value="{{ sala.pk }}">{{ sala.nome_sala }}</option>
{% endfor %}

doctrainingapp/templates/solicitacao_alterar_caso_clinico.html
{% include 'cabecalho2.html' %}

<script language="Javascript">

function aceitarAlteracao(id) {
   if (confirm("Tem certeza que deseja aceitar a alteração desse dado?")) {
     location.href="/casos_clinicos/solicitacoes/aceitar/"+id;

   }
}

function recusarAlteracao(id) {
   if (confirm("Tem certeza que deseja aceitar a alteração desse dado?")) {
     location.href="/casos_clinicos/solicitacoes/rejeitar/"+id;
   }
}

</script>


<h1>
  Hospital
</h1>

{% if messages %}
    <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.tags == 'success' %}
                        <font color="green">{{ message }}</font>
                    {% elif message.tags == 'error' %}
                        <font color="red">{{ message }}</font>
                    {% else %}
                        <!-- warning -->
                        <font color="blue">{{ message }}</font>
                    {% endif %}
                </li>
            {% endfor %}
    </ul>
{% endif %}


<p></p>
<h3>Solicitação de Alteração de Amostras de Doenças</h3>
<p></p>
<!-- <div style="overflow: auto; border:solid 1px;""> -->
<!-- <div style="overflow: auto; width: 1340px"> -->

<p></p>
<!-- <div style="overflow: auto; width: 100%; height: 500px; border:solid 1px; position: relative;"> -->
  <!-- <table class="ui celled striped table"> -->
<div class="dimmable">
    <div class="ui active inverted dimmer">
      <div class="ui active centered inline loader"></div>
      Carregando
    </div>
<table id="example" class="ui celled table" style="width:100%">
    <thead>
      <tr>
        <!-- Colunas da tabela -->
        <th>Data</th>
        <th>Solicitante</th>
        <th>Tipo</th>
        <th>Doença</th>
        <th>Sintoma(s)</th>
        <th>Nova Doença</th>
        <th>Novo(s) Sintoma(s)</th>
        {%if request.user.is_staff %}
          <th></th>
          <th></th>
        {% endif %}
        <!-- colunas da tabela -->
      </tr>
    </thead>

  <!--  Opções em cima da tabela-->

    <tbody>
      <!-- <tr><td>Dados</td></tr> -->

      <!-- {% for solicitacao,x in dados_zipado  %}
            <tr>
              <td> <b>{{solicitacao.pk}}</b> </td>
              <td> <b>{{solicitacao}}</b> </td>
              <td> <b> {{x}}</b> </td>
              <td> <a href="{% url 'doctrainingapp:solicitar_editar_caso_clinico' solicitacao.pk  %}" class="ui button" > Editar </a> </td>
              <td> <a class="ui red button" type="submit" onclick="confirmExclusao({{solicitacao.pk}})"  > Remover Amostra </a> </td>
            </tr>
      {% endfor %} -->
      {% for solicitacao in solicitacao_alterar_caso_clinico  %}
            <tr>
              <td> <b>{{solicitacao.data_solicitacao}}</b> </td>
              <td> <b>{{solicitacao.solicitante_DEF}}</b> </td>
              <td> <b class="ui {{solicitacao.cor_DEF}} label">{{solicitacao.tipo_alteracao_DEF}}</b> </td>
              <td> <b>{{solicitacao.nome_doenca_antigo_DEF}}</b> </td>
              <td> <b>{{solicitacao.sintomas_antigo_DEF}}</b> </td>
              <td> <b>{{solicitacao.nome_doenca_novo_DEF}}</b> </td>
              <td> <b>{{solicitacao.sintomas_novos_DEF}}</b> </td>
              {%if request.user.is_staff %}
                  <td> <a class="ui green button" type="submit" onclick="aceitarAlteracao({{solicitacao.pk}})"  > Aceitar </a> </td>
                  <td> <a class="ui red button" type="submit" onclick="recusarAlteracao({{solicitacao.pk}})"  > Recusar </a> </td>
              {% endif %}
            </tr>
      {% endfor %}

    </tbody>
  </table>

</div>









</div>

</div>
<!-- Cabecalho -->

<div>



{% include 'rodape.html' %}

doctrainingapp/templates/teste.html
{% include 'cabecalho2.html' %}

<h1>
  Fases
</h1>

{% if messages %}
    <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.tags == 'success' %}
                        <font color="green">{{ message }}</font>
                    {% elif message.tags == 'error' %}
                        <font color="red">{{ message }}</font>
                    {% else %}
                        <!-- warning -->
                        <font color="blue">{{ message }}</font>
                    {% endif %}
                </li>
            {% endfor %}
    </ul>
{% endif %}


<a href="{% url 'doctrainingapp:nova_fase'%}" class="ui button positive" > Nova Fase </a>


<p></p>
<!-- <div style="overflow: auto; width: 100%; height: 500px; border:solid 1px; position: relative;"> -->
  <!-- <table class="ui celled striped table"> -->
<div class="dimmable">

  <table id="example" class="ui celled table" style="width:100%">
    <thead>
      <tr>
        <!-- Colunas da tabela -->
        <th>Caso Clinico</th>
        <th>Fase</th>
        <th>Descrição</th>
        <th>Quantidade Pergunta(s)</th>
        <th>Criado por</th>
        <th>Data Abertura</th>
        <!-- colunas da tabela -->
        <th></th>
        <th></th>
        <!-- <th></th> -->
        <!-- <th colspan="3"> </th> -->
      </tr>
    </thead>

  <!--  Opções em cima da tabela-->

    <tbody>
      {% for fase in fases  %}
            <tr>
              <td><b> {{fase.caso_clinico}} </b></td>
              <td><b> {{fase.nome_fase}} </b></td>
              {% if fase.descricao  %}
                    <td> {{fase.descricao_limitado}}...</td>
              {% else %}
                    <td>  </td>
               {% endif %}
              <td> {{fase.quantidade_perguntas}} Pergunta(s)</td>
              <td> {{fase.responsavel_fase}} </td>
              <td> {{fase.data_criacao}} </td>
              <td>

                  {% if request.user.pk == fase.responsavel_fase.pk or request.user.is_staff %}
                      <a href="{% url 'doctrainingapp:todas_fases' fase.pk  %}" class="ui blue button" > Visualizar   <i class="folder open icon"></i> </a>
                  {% endif %}
              </td>
              <td>
                  {% if request.user.pk == fase.responsavel_fase.pk %}
                      <a href="{% url 'doctrainingapp:editar_fase' fase.pk  %}" class="ui button" >   Editar <i class="edit outline icon"></i> </a>
                  {% endif %}
              </td>
              <!-- <td>
                  {% if request.user.pk == sala.responsavel_sala.pk or request.user.is_staff%}
                      <a href="{% url 'doctrainingapp:delete_sala' sala.pk  %}" class="ui red button" >   Deletar </a>
                  {% endif %}
              </td> -->


            </tr>
      {% endfor %}

    </tbody>
  </table>

</div>













</div>

</div>
<!-- Cabecalho -->

<div>



{% include 'rodape.html' %}